# Generated by Django 5.1.1 on 2024-09-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='state',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Open'), (2, 'Freeze')], default=1),
        ),
    ]
