# Generated by Django 5.1.1 on 2024-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_block_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='idea_ballance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='matter_ballance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tg_user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
